### PR TITLE
BUGFIX: Adjust to BaseURI change #1755

### LINKED ISSUE #11: Flow base dist 6.0.0 triggers Undefined class constant 'BASE_URI'
### Description

Flow base dist 6.0.0 triggers `Undefined class constant 'BASE_URI'`

### Steps to Reproduce

1. `composer create-project --keep-vcs neos/flow-base-distribution Quickstart`
2. `cd Quickstart`
3. `./flow server:run`
4. open http://127.0.0.1:8081/flow/welcome

#### Expected behavior

The welcome screen.

#### Actual behavior

Key | Value
-|-
Exception Code | 0
Exception Type | Error
Thrown in File | Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Welcome_Controller_StandardController.php
Line | 39
Original File | Packages/Application/Neos.Welcome/Classes/Controller/StandardController.php

### Affected Versions

Flow: 6.0.0

### PR DESCRIPTION
**Pull request by albe**
Fixes #11

### CODE REVIEW

File: Classes/Controller/StandardController.php [hunk 1]
```diff
@@ -36,7 +36,7 @@ public function indexAction()
         $this->view->assign('flowPathWeb', realpath(FLOW_PATH_WEB));
         $this->view->assign('isPackageAvailable', $this->packageManager->isPackageAvailable('MyCompany.MyPackage'));
 
-        $baseUri = $this->request->getHttpRequest()->getAttribute(ServerRequestAttributes::BASE_URI);
+        $baseUri = (string)RequestInformationHelper::generateBaseUri($this->request->getHttpRequest());
         $this->view->assign('baseUri', (string)$baseUri);
```
Comment (kdambekalns) [inline Classes/Controller/StandardController.php]: Since it is cast to string above already…
```suggestion
        $this->view->assign('baseUri', $baseUri);
```

**Review by kdambekalns — APPROVED** [review]

**Comment by albe** [comment]
I mean, we probably could somehow get rid of this baseUri view variable alltogether, but that would require some assessment on it's use.

**Review by kdambekalns — COMMENTED** [review]
BTW: What is the advantage of `RequestInformationHelper` over `$baseUri = (string)$this->baseUriProvider->getConfiguredBaseUriOrFallbackToCurrentRequest();` in such a case?

File: Classes/Controller/StandardController.php [hunk 2]
```diff
@@ -36,8 +36,8 @@ public function indexAction()
         $this->view->assign('flowPathWeb', realpath(FLOW_PATH_WEB));
         $this->view->assign('isPackageAvailable', $this->packageManager->isPackageAvailable('MyCompany.MyPackage'));
 
-        $baseUri = $this->request->getHttpRequest()->getAttribute(ServerRequestAttributes::BASE_URI);
-        $this->view->assign('baseUri', (string)$baseUri);
+        $baseUri = (string)RequestInformationHelper::generateBaseUri($this->request->getHttpRequest());
```
Comment (kdambekalns) [inline Classes/Controller/StandardController.php]:
```suggestion
        $baseUri = (string)Helper\RequestInformationHelper::generateBaseUri($this->request->getHttpRequest());
```

**Review by kdambekalns — CHANGES_REQUESTED** [review]

**Comment by kdambekalns** [comment]
Ok, I took the freedom to replace this with a version known to be working (for me)… ;)

**Review by kdambekalns — APPROVED** [review]
